---
name: Test documentation

env:
  CI_FORCE_COLORS_SPHINX: --color

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - "!*"
    branches:
      - main
      - "test-me-*"

  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Tests on ${{ matrix.os }} with default python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Display Python version
        run: python --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pipx
        run: python -m pip install --upgrade pipx

      - name: Install tox via pipx
        run: pipx install tox

      - name: Run tests with tox except linkcheck and spelling
        if: runner.os != 'Linux'
        run: tox -m docs

      - name: Run all tests with tox
        if: runner.os == 'Linux'
        run: tox -m docs-full
